artifact_location: /home/guangzhi-tang/Documents/WoS2025/game_interface/runs/mlflow/0
creation_time: 1758891570980
experiment_id: '0'
last_update_time: 1758891570980
lifecycle_stage: active
name: Default
